name: flutter_analyze_reporter_2
description: Parse Flutter analyze output to display it within GitLab Code Quality Widget
version: 0.2.3
homepage: https://github.com/prasadsunny1/flutter_analyze_reporter
repository: https://github.com/prasadsunny1/flutter_analyze_reporter
issue_tracker: https://github.com/prasadsunny1/flutter_analyze_reporter/issues

executables:
  flutter_analyze_reporter_2:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  ansicolor: ^2.0.3
  args: ^2.7.0
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  xml: ^6.5.0
dev_dependencies:
  flutter_lints: ^2.0.3
  test: ^1.26.3
